user:
  maximum_name: 50
  maximum_email: 255
  minimum_password: 6
category:
  maximum_name: 30
  role_default: 0
category:
  maximum_name: 30
session:
  remember: "1"
currency:
  usa: $
order_details:
  tour_name: 30
