user:
  maximum_name: 50
  maximum_email: 255
  minimum_password: 6
category:
  maximum_name: 30
<<<<<<< HEAD
=======
  role_default: 0
category:
  maximum_name: 30
session:
  remember: "1"
>>>>>>> a5f22ce... signup-login-logout
